trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - script: |
      cd Shopify-backend
      cd controllers
      npm install
      npm run test
    displayName: "npm run test"
