#create a PRODUCT
POST http://localhost:4500/products
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdlM2I3ZDJiLTQ3Y2YtNDE0MS1hMGYyLWExZTNhNDMxYmI5ZSIsInVzZXJuYW1lIjoibmdhdGlhIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIxMjM0NTY3OCIsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTIxVDE1OjQzOjUxLjk1M1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJpYXQiOjE2OTI2MjIzNzcsImV4cCI6MTY5MjYyNTk3N30.08gTBIYgCIr0rrjS-HSr1OI7WUvWUTwkm4a50HHLxVs

{
    "name": "Range Rover",
    "description": "With its commanding presence, luxurious features, and superior performance, this Range Rover embodies both style and power. Meticulously cared for, this vehicle exudes elegance and refinement at every turn.",
    "price": "7000000.00",
    "category": "car",
    "num_items": "1"
}



### GET ALL PRODUCTS
GET http://localhost:4500/products
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdlM2I3ZDJiLTQ3Y2YtNDE0MS1hMGYyLWExZTNhNDMxYmI5ZSIsInVzZXJuYW1lIjoibmdhdGlhIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIxMjM0NTY3OCIsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTIxVDE1OjQzOjUxLjk1M1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJpYXQiOjE2OTI2ODE4MTgsImV4cCI6MTY5MjY4NTQxOH0.4MzaIDIU4lBmsh65v0SEvul59uiTozkFn1G6Lmp0VGc

### GET ONE PRODUCTS
GET http://localhost:4500/products/40582d44-728b-42ba-b5d3-fee702175e4d
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRiMjIzZjMxLTA1ZTYtNDU3Ny05NjU5LTU1MjNjNWM4ZTI2MyIsImZ1bGxfbmFtZSI6Ik1pbGxhIEplc3NvIiwiZW1haWwiOiJtaWxsYUBnbWFpbC5jb20iLCJhc3NpZ25lZFByb2plY3QiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjkxMDk0NDg3LCJleHAiOjE2OTEwOTgwODd9.CsVl8qiUIZNnPQJHoB4GSGHUnRwzx5UhBkxt5OgP6HI

### UPDATING PRODUCT
PUT http://localhost:4500/products/40582d44-728b-42ba-b5d3-fee702175e4d
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdlM2I3ZDJiLTQ3Y2YtNDE0MS1hMGYyLWExZTNhNDMxYmI5ZSIsInVzZXJuYW1lIjoibmdhdGlhIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIxMjM0NTY3OCIsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTIxVDE1OjQzOjUxLjk1M1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJpYXQiOjE2OTI3MjQ0NjksImV4cCI6MTY5MjcyODA2OX0.ZHrF0LvUjc5hbdqbiLyPJSIla3BpirWwFVwDi9o9Jn0

{
    "name": "Sing some more",
    "description": "It works, don’t touch!",
    "price": "2023/8/5",
    "category": "electricals",
    "image": "2023/8/5",
    "num_items": "2023"

}

###delete product
DELETE http://localhost:4500/products/24f539b3-98de-48e8-afaf-119f9a4e08e7
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdlM2I3ZDJiLTQ3Y2YtNDE0MS1hMGYyLWExZTNhNDMxYmI5ZSIsInVzZXJuYW1lIjoibmdhdGlhIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIxMjM0NTY3OCIsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTIxVDE1OjQzOjUxLjk1M1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJpYXQiOjE2OTI3MjQ0NjksImV4cCI6MTY5MjcyODA2OX0.ZHrF0LvUjc5hbdqbiLyPJSIla3BpirWwFVwDi9o9Jn0

###assign product
# PUT http://localhost:4500/users/assign
# Content-Type: application/json

# {
#     "project_id": "53543c52-4e36-4ec9-ac80-7c70a9c9cfbe",
#     "user_id": "a5907d51-f0d0-425e-b601-872d48d53a04"    
# }


###complete project
# POST http://localhost:4500/users/complete
# Content-Type: application/json

# {
#     "project_id": "0b3a8000-3557-4ebb-bf4b-2a660c02f41d",
#     "user_id": "a5907d51-f0d0-425e-b601-872d48d53a04"    
# }

### register
POST  http://localhost:4500/users/register
Content-Type: application/json

{
   
    "username": "Jonhte",
    "email":"johngessko@gmail.com",
    "password":"12345678",
    "phone_number": "12345678"
}


### login
POST  http://localhost:4500/users/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"12345678"
}

###
GET http://localhost:4500/users/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVkNTNkMWYzLTUyNDItNDIwYi1iZjQyLTAyMzA0NmExZDhhOSIsImZ1bGxfbmFtZSI6Ik1pbGxhIFdhY2hpcmEgU2lsb21hIiwiZW1haWwiOiJpZ25pdDNncmFwaGljc0BnbWFpbC5jb20iLCJhc3NpZ25lZFByb2plY3QiOm51bGwsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MTY2MDM0OCwiZXhwIjoxNjkxNjYzOTQ4fQ.LXJkVJhFNpGESbG79zli1_uPcUGLRTzVLzbZ53H-cEg

###  
GET http://localhost:4500/users/allusers
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVkNTNkMWYzLTUyNDItNDIwYi1iZjQyLTAyMzA0NmExZDhhOSIsImZ1bGxfbmFtZSI6Ik1pbGxhIFdhY2hpcmEgU2lsb21hIiwiZW1haWwiOiJpZ25pdDNncmFwaGljc0BnbWFpbC5jb20iLCJhc3NpZ25lZFByb2plY3QiOm51bGwsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MTY2MDM0OCwiZXhwIjoxNjkxNjYzOTQ4fQ.LXJkVJhFNpGESbG79zli1_uPcUGLRTzVLzbZ53H-cEg