### register
POST  http://localhost:4500/users/register
Content-Type: application/json

{
   
    "username": "Jason",
    "email":"openo2000@gmail.com",
    "password":"12345678",
    "phone_number": "12345678"
}


### login
POST  http://localhost:4500/users/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"12345678"
}


###CREATE A PRODUCT
POST http://localhost:4500/products
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikphc29uIiwiZW1haWwiOiJvcGVubzIwMDBAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkMlBWUVE3enF4Vy92ZWV4ZmxMUkFZdTlHUC9FMUU4RDNORFJVaUFQMDR6MEFTSElvNldCUFciLCJwaG9uZV9udW1iZXIiOjEyMzQ1Njc4LCJjcmVhdGVkX2F0IjoiMjAyMy0wOC0yMlQyMzowMzoxMi41MTNaIiwidXBkYXRlZF9hdCI6bnVsbCwiY2FydF9pZCI6bnVsbCwicmVzZXRUb2tlbiI6bnVsbCwicmVzZXRUb2tlbkV4cGlyeSI6bnVsbCwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyNzM0NjM3LCJleHAiOjE2OTI3MzgyMzd9.OBFKi7WEOdmSSP9oJGbarCdS42JKxIZnn1pZZb1oB0Y


{
    "name": "JOHN MIILA NGATIA",
    "description": "It ndgcvworks, don’t touch!",
    "price": "2023/8/5",
    "category": "2023/8/5",
    "image": "2023/8/5",
    "num_items": "2023"
}



### GET ALL PRODUCTS
GET http://localhost:4500/products
# token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2ODIxNDRlLTZiY2MtNDE3Yi04YzQ5LWQzZTY4OWFhYzA5NiIsInVzZXJuYW1lIjoiSm9oZ25oIiwiZW1haWwiOiJqb2huSmdlc3Nrb0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIxMjM0NTY3OCIsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTIxVDExOjUzOjI4LjUxN1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJpYXQiOjE2OTI2MDg5NTAsImV4cCI6MTY5MjYxMjU1MH0.6lDSnhAw1fBJX2qDtsXRNHvTJpEoWXNxLo6__-iJ-tM


### GET ONE PRODUCTS
GET http://localhost:4500/products/dbef84e5-1bdc-4014-bd79-fde26a0a9446
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRiMjIzZjMxLTA1ZTYtNDU3Ny05NjU5LTU1MjNjNWM4ZTI2MyIsImZ1bGxfbmFtZSI6Ik1pbGxhIEplc3NvIiwiZW1haWwiOiJtaWxsYUBnbWFpbC5jb20iLCJhc3NpZ25lZFByb2plY3QiOm51bGwsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjkxMDk0NDg3LCJleHAiOjE2OTEwOTgwODd9.CsVl8qiUIZNnPQJHoB4GSGHUnRwzx5UhBkxt5OgP6HI

### UPDATING PRODUCT
PUT http://localhost:4500/products/dbef84e5-1bdc-4014-bd79-fde26a0a9446
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikphc29uIiwiZW1haWwiOiJvcGVubzIwMDBAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkMlBWUVE3enF4Vy92ZWV4ZmxMUkFZdTlHUC9FMUU4RDNORFJVaUFQMDR6MEFTSElvNldCUFciLCJwaG9uZV9udW1iZXIiOjEyMzQ1Njc4LCJjcmVhdGVkX2F0IjoiMjAyMy0wOC0yMlQyMzowMzoxMi41MTNaIiwidXBkYXRlZF9hdCI6bnVsbCwiY2FydF9pZCI6bnVsbCwicmVzZXRUb2tlbiI6bnVsbCwicmVzZXRUb2tlbkV4cGlyeSI6bnVsbCwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyNzM0NjM3LCJleHAiOjE2OTI3MzgyMzd9.OBFKi7WEOdmSSP9oJGbarCdS42JKxIZnn1pZZb1oB0Y

{
    "name": "BIG JESSY",
    "description": "It works, don’t touch!",
    "price": "2023/8/5",
    "category": "electricals",
    "image": "2023/8/5",
    "num_items": "2023"

}

###delete product
DELETE http://localhost:4500/products/dbef84e5-1bdc-4014-bd79-fde26a0a9446
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikphc29uIiwiZW1haWwiOiJvcGVubzIwMDBAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkMlBWUVE3enF4Vy92ZWV4ZmxMUkFZdTlHUC9FMUU4RDNORFJVaUFQMDR6MEFTSElvNldCUFciLCJwaG9uZV9udW1iZXIiOjEyMzQ1Njc4LCJjcmVhdGVkX2F0IjoiMjAyMy0wOC0yMlQyMzowMzoxMi41MTNaIiwidXBkYXRlZF9hdCI6bnVsbCwiY2FydF9pZCI6bnVsbCwicmVzZXRUb2tlbiI6bnVsbCwicmVzZXRUb2tlbkV4cGlyeSI6bnVsbCwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyNzM0NjM3LCJleHAiOjE2OTI3MzgyMzd9.OBFKi7WEOdmSSP9oJGbarCdS42JKxIZnn1pZZb1oB0Y


###add product to cart
POST http://localhost:4500/cart/add-to-cart
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikphc29uIiwiZW1haWwiOiJvcGVubzIwMDBAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkMlBWUVE3enF4Vy92ZWV4ZmxMUkFZdTlHUC9FMUU4RDNORFJVaUFQMDR6MEFTSElvNldCUFciLCJwaG9uZV9udW1iZXIiOjEyMzQ1Njc4LCJjcmVhdGVkX2F0IjoiMjAyMy0wOC0yMlQyMzowMzoxMi41MTNaIiwidXBkYXRlZF9hdCI6bnVsbCwiY2FydF9pZCI6bnVsbCwicmVzZXRUb2tlbiI6bnVsbCwicmVzZXRUb2tlbkV4cGlyeSI6bnVsbCwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyNzM0NjM3LCJleHAiOjE2OTI3MzgyMzd9.OBFKi7WEOdmSSP9oJGbarCdS42JKxIZnn1pZZb1oB0Y

{
  "user_id": "77e9931a-30b5-4120-9e99-e42ccae6ffa3",
  "product_id": "2f84cb0d-f82b-4d48-b951-296f367a84ed"     
}



### complete project
# POST http://localhost:4500/cart/complete
# Content-Type: application/json

# {
#     "project_id": "0b3a8000-3557-4ebb-bf4b-2a660c02f41d",
#     "user_id": "a5907d51-f0d0-425e-b601-872d48d53a04"    
# }





### reset password
POST  http://localhost:4500/reset/resetPassword
Content-Type: application/json

{
    "email": "ngatiamwai25@gmail.com"   
}

### reset password
POST  http://localhost:4500/reset/updatePassword
Content-Type: application/json

{
    "resetToken": "7de101ab-8ab8-4946-a999-b2e73a1cd2d7",
    "newPassword": "milla"
    
}






###check user -ignore this end point
# GET http://localhost:4500/users/check
# token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVkNTNkMWYzLTUyNDItNDIwYi1iZjQyLTAyMzA0NmExZDhhOSIsImZ1bGxfbmFtZSI6Ik1pbGxhIFdhY2hpcmEgU2lsb21hIiwiZW1haWwiOiJpZ25pdDNncmFwaGljc0BnbWFpbC5jb20iLCJhc3NpZ25lZFByb2plY3QiOm51bGwsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MTY2MDM0OCwiZXhwIjoxNjkxNjYzOTQ4fQ.LXJkVJhFNpGESbG79zli1_uPcUGLRTzVLzbZ53H-cEg

### get all user items on cart 
GET http://localhost:4500/cart/cart-items
# token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbHMiLCJlbWFpbCI6ImRhbmllbHlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkT0piOWtydkJXeGx4WlRHeFBpMUJMdWk0TjlFZ1NQWG14U3BWNnRSSk8wZFVPTnFVMFpHUWEiLCJwaG9uZV9udW1iZXIiOjEyMzQ1Njc4LCJjcmVhdGVkX2F0IjoiMjAyMy0wOC0yMlQxNjowMDoyOS43NjdaIiwidXBkYXRlZF9hdCI6bnVsbCwiY2FydF9pZCI6bnVsbCwicmVzZXRUb2tlbiI6bnVsbCwicmVzZXRUb2tlbkV4cGlyeSI6bnVsbCwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyNzEyMTI2LCJleHAiOjE2OTI3MTU3MjZ9.6c1ZwuOIyauls1mLvBs5W_chtPWbX3fO0iJDpCLIm88
Content-Type: application/json

{
    "userId": "33c97805-0b62-423c-b954-bce6c73eac02" 
}

### get all users 
GET http://localhost:4500/users/allusers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5nYXRpYSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkSHZpeG9qQUlwWHRjZXhpZzRSaEZ1dXdFV1VsUFdqYVM0T1YyQUMxWUZSMDVmV1p5TUpUOFMiLCJwaG9uZV9udW1iZXIiOiIxMjM0NTY3OCIsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTIxVDE1OjQzOjUxLjk1M1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJpYXQiOjE2OTI3NDE2NDYsImV4cCI6MTY5Mjc0NTI0Nn0.NfsVfPWuUsUa8PUYLZuBtnUwFt2db4LgedOaWwVRP5Y


###delete user-soft delete
DELETE http://localhost:4500/users/softdelete/33c97805-0b62-423c-b954-bce6c73eac02
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbHMiLCJlbWFpbCI6Implc3N5b3Blbm8yMDAwQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JE53T2FZRzZjZ2NTQW1BT0FNeGRJc2VrOTNtV1ZESjFGeWdoZkczNkM5R3laM2VYSzhZc0ZTIiwicGhvbmVfbnVtYmVyIjoxMjM0NTY3OCwiY3JlYXRlZF9hdCI6IjIwMjMtMDgtMjJUMjE6MDc6MTAuMDQ3WiIsInVwZGF0ZWRfYXQiOm51bGwsImNhcnRfaWQiOm51bGwsInJlc2V0VG9rZW4iOm51bGwsInJlc2V0VG9rZW5FeHBpcnkiOm51bGwsImRlbGV0ZWRfYXQiOm51bGwsImlhdCI6MTY5MjcyODczMiwiZXhwIjoxNjkyNzMyMzMyfQ.76tcf6ufhqD6NP4P1npxYS6MSw50Xj8x_Q0lfTuG0YA


###delete user-permanent delete
DELETE http://localhost:4500/permanentdelete/:id'
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2ODIxNDRlLTZiY2MtNDE3Yi04YzQ5LWQzZTY4OWFhYzA5NiIsInVzZXJuYW1lIjoiSm9oZ25oIiwiZW1haWwiOiJqb2huSmdlc3Nrb0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIxMjM0NTY3OCIsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTIxVDExOjUzOjI4LjUxN1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJpYXQiOjE2OTI2MDg5NTAsImV4cCI6MTY5MjYxMjU1MH0.6lDSnhAw1fBJX2qDtsXRNHvTJpEoWXNxLo6__-iJ-tM


### UPDATING USER
PUT http://localhost:4500/users/33c97805-0b62-423c-b954-bce6c73eac02
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaGduaCIsImVtYWlsIjoiam9obkpnZXNza29AZ21haWwuY29tIiwicGhvbmVfbnVtYmVyIjoiMTIzNDU2NzgiLCJjcmVhdGVkX2F0IjoiMjAyMy0wOC0yMVQxMTo1MzoyOC41MTdaIiwidXBkYXRlZF9hdCI6bnVsbCwiY2FydF9pZCI6bnVsbCwiaWF0IjoxNjkyNjE1OTQ5LCJleHAiOjE2OTI2MTk1NDl9.0N4dhyY0QG-7sgk2BEVHE5jFhtjelVNuel9sqAobICk

{
    "username": "Sing ",
    "email": "behlian@gmail.com",
    "phone_number": "2023744585"
    

}

