### register
POST  http://localhost:4500/users/register
Content-Type: application/json

{
   
    "username": "JaTJmmnaduong",
    "email":"jadunommmTng@gmail.com",
    "password":"12345678",
    "phone_number": "12345678"
}


### login
POST  http://localhost:4500/users/login
Content-Type: application/json

{
    "email":"jadunommmTng@gmail.com",
    "password":"12345678"
}






###CREATE A PRODUCT
POST http://localhost:4500/products
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphVEptbW5hZHVvbmciLCJlbWFpbCI6ImphZHVub21tbVRuZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwNSQuZDkzSFEudUhBT1psTTZib1FBZ1V1TktGb0dvbURFRFJIWUIub3F4ZlU1dVdLUjZZLkZEYSIsInBob25lX251bWJlciI6MTIzNDU2NzgsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTI3VDE0OjI1OjIxLjQ5M1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJyZXNldFRva2VuIjpudWxsLCJyZXNldFRva2VuRXhwaXJ5IjpudWxsLCJkZWxldGVkX2F0IjpudWxsLCJpYXQiOjE2OTMxMzU1NjAsImV4cCI6MTY5MzE3MTU2MH0.CiBbQp6afPI3p7f_IV1tqdpZPgnpSfp9lVM1peA2cxs


{
    "name": "MIILA NGATIA product",
    "description": "It ndgcvworks, don’t touch!",
    "price": "2023/8/5",
    "category": "2023/8/5",
    "image": "2023/8/5",
    "num_items": "2023"
}



### GET ALL PRODUCTS
GET http://localhost:4500/products
# token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2ODIxNDRlLTZiY2MtNDE3Yi04YzQ5LWQzZTY4OWFhYzA5NiIsInVzZXJuYW1lIjoiSm9oZ25oIiwiZW1haWwiOiJqb2huSmdlc3Nrb0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIxMjM0NTY3OCIsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTIxVDExOjUzOjI4LjUxN1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJpYXQiOjE2OTI2MDg5NTAsImV4cCI6MTY5MjYxMjU1MH0.6lDSnhAw1fBJX2qDtsXRNHvTJpEoWXNxLo6__-iJ-tM


### GET ONE PRODUCTS
GET http://localhost:4500/products/2f84cb0d-f82b-4d48-b951-296f367a84ed
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbHMiLCJlbWFpbCI6Implc3N5b3Blbm8yMDAwQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JHk4eEQxRks0UWFxTC5ScFhtYXYvWWVXblBoMlVyNktqYmU5bkJEcWgwck40b1dreXdJc2cyIiwicGhvbmVfbnVtYmVyIjoxMjM0NTY3OCwiY3JlYXRlZF9hdCI6IjIwMjMtMDgtMjJUMjE6MDc6MTAuMDQ3WiIsInVwZGF0ZWRfYXQiOm51bGwsImNhcnRfaWQiOm51bGwsInJlc2V0VG9rZW4iOiI1YjM4MjIzZC1mZTU2LTQxMjYtYmIyOC02MmVhMWQwNWIzYjgiLCJyZXNldFRva2VuRXhwaXJ5IjoiMjAyMy0wOC0yNFQxMToyMToyOS40MjNaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyODc0MzY5LCJleHAiOjE2OTI5MTAzNjl9.6E80VEulawirccwBQzS1Ftz8Rp_j596HOYz6OLeKfAE
### UPDATING PRODUCT
PUT http://localhost:4500/products/2f84cb0d-f82b-4d48-b951-296f367a84ed
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbHMiLCJlbWFpbCI6Implc3N5b3Blbm8yMDAwQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JHk4eEQxRks0UWFxTC5ScFhtYXYvWWVXblBoMlVyNktqYmU5bkJEcWgwck40b1dreXdJc2cyIiwicGhvbmVfbnVtYmVyIjoxMjM0NTY3OCwiY3JlYXRlZF9hdCI6IjIwMjMtMDgtMjJUMjE6MDc6MTAuMDQ3WiIsInVwZGF0ZWRfYXQiOm51bGwsImNhcnRfaWQiOm51bGwsInJlc2V0VG9rZW4iOiI1YjM4MjIzZC1mZTU2LTQxMjYtYmIyOC02MmVhMWQwNWIzYjgiLCJyZXNldFRva2VuRXhwaXJ5IjoiMjAyMy0wOC0yNFQxMToyMToyOS40MjNaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyODc0MzY5LCJleHAiOjE2OTI5MTAzNjl9.6E80VEulawirccwBQzS1Ftz8Rp_j596HOYz6OLeKfAE

{
    "name": "BIG JESSY UPDATED",
    "description": "It works, don’t touch!",
    "price": "2023/8/5",
    "category": "electricals",
    "image": "2023/8/5",
    "num_items": "2023"

}

###delete product
DELETE http://localhost:4500/products/2f84cb0d-f82b-4d48-b951-296f367a84ed
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbHMiLCJlbWFpbCI6Implc3N5b3Blbm8yMDAwQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JHk4eEQxRks0UWFxTC5ScFhtYXYvWWVXblBoMlVyNktqYmU5bkJEcWgwck40b1dreXdJc2cyIiwicGhvbmVfbnVtYmVyIjoxMjM0NTY3OCwiY3JlYXRlZF9hdCI6IjIwMjMtMDgtMjJUMjE6MDc6MTAuMDQ3WiIsInVwZGF0ZWRfYXQiOm51bGwsImNhcnRfaWQiOm51bGwsInJlc2V0VG9rZW4iOiI1YjM4MjIzZC1mZTU2LTQxMjYtYmIyOC02MmVhMWQwNWIzYjgiLCJyZXNldFRva2VuRXhwaXJ5IjoiMjAyMy0wOC0yNFQxMToyMToyOS40MjNaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyODc0MzY5LCJleHAiOjE2OTI5MTAzNjl9.6E80VEulawirccwBQzS1Ftz8Rp_j596HOYz6OLeKfAE

###add product to cart
POST http://localhost:4500/cart/add-to-cart
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphVEptbW5hZHVvbmciLCJlbWFpbCI6ImphZHVub21tbVRuZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwNSQuZDkzSFEudUhBT1psTTZib1FBZ1V1TktGb0dvbURFRFJIWUIub3F4ZlU1dVdLUjZZLkZEYSIsInBob25lX251bWJlciI6MTIzNDU2NzgsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTI3VDE0OjI1OjIxLjQ5M1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJyZXNldFRva2VuIjpudWxsLCJyZXNldFRva2VuRXhwaXJ5IjpudWxsLCJkZWxldGVkX2F0IjpudWxsLCJpYXQiOjE2OTMxMzU1NjAsImV4cCI6MTY5MzE3MTU2MH0.CiBbQp6afPI3p7f_IV1tqdpZPgnpSfp9lVM1peA2cxs

{
  
  "user_id": "745bcdf8-6d2d-4f67-9887-2d29038374db",
  "product_id": "678f42e8-0fcd-4a8d-b763-11ccc147a469"     

}

###checkout from cart
POST http://localhost:4500/cart/checkout
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphVEptbW5hZHVvbmciLCJlbWFpbCI6ImphZHVub21tbVRuZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwNSQuZDkzSFEudUhBT1psTTZib1FBZ1V1TktGb0dvbURFRFJIWUIub3F4ZlU1dVdLUjZZLkZEYSIsInBob25lX251bWJlciI6MTIzNDU2NzgsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTI3VDE0OjI1OjIxLjQ5M1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJyZXNldFRva2VuIjpudWxsLCJyZXNldFRva2VuRXhwaXJ5IjpudWxsLCJkZWxldGVkX2F0IjpudWxsLCJpYXQiOjE2OTMxMzU1NjAsImV4cCI6MTY5MzE3MTU2MH0.CiBbQp6afPI3p7f_IV1tqdpZPgnpSfp9lVM1peA2cxs

{
  "user_id": "745bcdf8-6d2d-4f67-9887-2d29038374db" 
}



### complete project
# POST http://localhost:4500/cart/complete
# Content-Type: application/json

# {
#     "project_id": "0b3a8000-3557-4ebb-bf4b-2a660c02f41d",
#     "user_id": "a5907d51-f0d0-425e-b601-872d48d53a04"    
# }





### reset password
POST  http://localhost:4500/reset/resetPassword
Content-Type: application/json

{
    "email": "jessyopeno2000@gmail.com"   
}

### reset password
POST  http://localhost:4500/reset/updatePassword
Content-Type: application/json

{
    "resetToken": "2953a64d-740f-4ee3-a22e-38e7ae21ea3b",
    "newPassword": "milla789"
    
}






###check user -ignore this end point
# GET http://localhost:4500/users/check
# token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVkNTNkMWYzLTUyNDItNDIwYi1iZjQyLTAyMzA0NmExZDhhOSIsImZ1bGxfbmFtZSI6Ik1pbGxhIFdhY2hpcmEgU2lsb21hIiwiZW1haWwiOiJpZ25pdDNncmFwaGljc0BnbWFpbC5jb20iLCJhc3NpZ25lZFByb2plY3QiOm51bGwsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MTY2MDM0OCwiZXhwIjoxNjkxNjYzOTQ4fQ.LXJkVJhFNpGESbG79zli1_uPcUGLRTzVLzbZ53H-cEg

### get all user items on cart 
GET http://localhost:4500/cart/cart-items
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbHMiLCJlbWFpbCI6Implc3N5b3Blbm8yMDAwQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JHk4eEQxRks0UWFxTC5ScFhtYXYvWWVXblBoMlVyNktqYmU5bkJEcWgwck40b1dreXdJc2cyIiwicGhvbmVfbnVtYmVyIjoxMjM0NTY3OCwiY3JlYXRlZF9hdCI6IjIwMjMtMDgtMjJUMjE6MDc6MTAuMDQ3WiIsInVwZGF0ZWRfYXQiOm51bGwsImNhcnRfaWQiOm51bGwsInJlc2V0VG9rZW4iOiI1YjM4MjIzZC1mZTU2LTQxMjYtYmIyOC02MmVhMWQwNWIzYjgiLCJyZXNldFRva2VuRXhwaXJ5IjoiMjAyMy0wOC0yNFQxMToyMToyOS40MjNaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyODc0MzY5LCJleHAiOjE2OTI5MTAzNjl9.6E80VEulawirccwBQzS1Ftz8Rp_j596HOYz6OLeKfAE
Content-Type: application/json

{
    "userId": "cda82a8b-ae1e-4d94-ad13-444e3c0fb55d" 
}

### get all user items on cartitems table for admin
GET http://localhost:4500/users/allcartitems
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbHMiLCJlbWFpbCI6Implc3N5b3Blbm8yMDAwQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JHk4eEQxRks0UWFxTC5ScFhtYXYvWWVXblBoMlVyNktqYmU5bkJEcWgwck40b1dreXdJc2cyIiwicGhvbmVfbnVtYmVyIjoxMjM0NTY3OCwiY3JlYXRlZF9hdCI6IjIwMjMtMDgtMjJUMjE6MDc6MTAuMDQ3WiIsInVwZGF0ZWRfYXQiOm51bGwsImNhcnRfaWQiOm51bGwsInJlc2V0VG9rZW4iOiI1YjM4MjIzZC1mZTU2LTQxMjYtYmIyOC02MmVhMWQwNWIzYjgiLCJyZXNldFRva2VuRXhwaXJ5IjoiMjAyMy0wOC0yNFQxMToyMToyOS40MjNaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyODc0MzY5LCJleHAiOjE2OTI5MTAzNjl9.6E80VEulawirccwBQzS1Ftz8Rp_j596HOYz6OLeKfAE




### get all users 
GET http://localhost:4500/users/allusers
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphVEptbW5hZHVvbmciLCJlbWFpbCI6ImphZHVub21tbVRuZ0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQwNSQuZDkzSFEudUhBT1psTTZib1FBZ1V1TktGb0dvbURFRFJIWUIub3F4ZlU1dVdLUjZZLkZEYSIsInBob25lX251bWJlciI6MTIzNDU2NzgsImNyZWF0ZWRfYXQiOiIyMDIzLTA4LTI3VDE0OjI1OjIxLjQ5M1oiLCJ1cGRhdGVkX2F0IjpudWxsLCJjYXJ0X2lkIjpudWxsLCJyZXNldFRva2VuIjpudWxsLCJyZXNldFRva2VuRXhwaXJ5IjpudWxsLCJkZWxldGVkX2F0IjpudWxsLCJpYXQiOjE2OTMxMzU1NjAsImV4cCI6MTY5MzE3MTU2MH0.CiBbQp6afPI3p7f_IV1tqdpZPgnpSfp9lVM1peA2cxs

###delete user-soft delete
DELETE http://localhost:4500/users/softdelete/61eefc5d-9de7-467c-bda4-1804b54be1ae
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbHMiLCJlbWFpbCI6Implc3N5b3Blbm8yMDAwQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JHk4eEQxRks0UWFxTC5ScFhtYXYvWWVXblBoMlVyNktqYmU5bkJEcWgwck40b1dreXdJc2cyIiwicGhvbmVfbnVtYmVyIjoxMjM0NTY3OCwiY3JlYXRlZF9hdCI6IjIwMjMtMDgtMjJUMjE6MDc6MTAuMDQ3WiIsInVwZGF0ZWRfYXQiOm51bGwsImNhcnRfaWQiOm51bGwsInJlc2V0VG9rZW4iOiI1YjM4MjIzZC1mZTU2LTQxMjYtYmIyOC02MmVhMWQwNWIzYjgiLCJyZXNldFRva2VuRXhwaXJ5IjoiMjAyMy0wOC0yNFQxMToyMToyOS40MjNaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyODc0MzY5LCJleHAiOjE2OTI5MTAzNjl9.6E80VEulawirccwBQzS1Ftz8Rp_j596HOYz6OLeKfAE


###delete user-permanent delete
DELETE http://localhost:4500/users/permanentdelete/61eefc5d-9de7-467c-bda4-1804b54be1ae
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbHMiLCJlbWFpbCI6Implc3N5b3Blbm8yMDAwQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JHk4eEQxRks0UWFxTC5ScFhtYXYvWWVXblBoMlVyNktqYmU5bkJEcWgwck40b1dreXdJc2cyIiwicGhvbmVfbnVtYmVyIjoxMjM0NTY3OCwiY3JlYXRlZF9hdCI6IjIwMjMtMDgtMjJUMjE6MDc6MTAuMDQ3WiIsInVwZGF0ZWRfYXQiOm51bGwsImNhcnRfaWQiOm51bGwsInJlc2V0VG9rZW4iOiI1YjM4MjIzZC1mZTU2LTQxMjYtYmIyOC02MmVhMWQwNWIzYjgiLCJyZXNldFRva2VuRXhwaXJ5IjoiMjAyMy0wOC0yNFQxMToyMToyOS40MjNaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyODc0MzY5LCJleHAiOjE2OTI5MTAzNjl9.6E80VEulawirccwBQzS1Ftz8Rp_j596HOYz6OLeKfAE


### UPDATING USER
PUT http://localhost:4500/users/33c97805-0b62-423c-b954-bce6c73eac02
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbmllbHMiLCJlbWFpbCI6Implc3N5b3Blbm8yMDAwQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDA1JHk4eEQxRks0UWFxTC5ScFhtYXYvWWVXblBoMlVyNktqYmU5bkJEcWgwck40b1dreXdJc2cyIiwicGhvbmVfbnVtYmVyIjoxMjM0NTY3OCwiY3JlYXRlZF9hdCI6IjIwMjMtMDgtMjJUMjE6MDc6MTAuMDQ3WiIsInVwZGF0ZWRfYXQiOm51bGwsImNhcnRfaWQiOm51bGwsInJlc2V0VG9rZW4iOiI1YjM4MjIzZC1mZTU2LTQxMjYtYmIyOC02MmVhMWQwNWIzYjgiLCJyZXNldFRva2VuRXhwaXJ5IjoiMjAyMy0wOC0yNFQxMToyMToyOS40MjNaIiwiZGVsZXRlZF9hdCI6bnVsbCwiaWF0IjoxNjkyODc0MzY5LCJleHAiOjE2OTI5MTAzNjl9.6E80VEulawirccwBQzS1Ftz8Rp_j596HOYz6OLeKfAE

{
    "username": "SingNGAA",
    "email": "behlian@gmail.com",
    "phone_number": "2023744585"
}

